name: FTP Deploy

on:
  push:
    branches:
      - main  # Укажите ветку, которая должна триггерить деплой

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Путь к файлам, которые вы хотите загрузить (./ — корень проекта)
        server-dir: /www/sto1region.store/  # Путь на вашем сервере
